version: '3.3'
services:

  elasticsearch:
    image: wutang/elasticsearch-shanghai-zone:6.3.2
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - aaq
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - MAX_LOCKED_MEMORY=unlimited
      - MAX_OPEN_FILES=131070
    ulimits:
      memlock: 9223372036854775807
    # networks:
    #   - aaq
 
  oap:
    build:
      context: ./oap
    # image: skywalking/oap:6.0.0-GA
    container_name: oap
    depends_on:
      - elasticsearch
    # links:
    #   - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    volumes:
      - ./oap/config:/skywalking/config:ro
    networks:
      - aaq
  ui:
    build:
      context: ./ui
    # image: skywalking/ui:6.0.0-GA
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8080:8080
    environment:
      collector.ribbon.listOfServers: oap:12800
      collector.ribbon.ReadTimeout: 20000
    # networks:
    #   - aaq

# volumes:
#   agent-data:

# networks:
#   aaq:
#     external: true